# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  
  build:
  
    runs-on: ubuntu-latest

    steps:
      - name: pull repo
        uses: actions/checkout@v3
 
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        continue-on-error: true

      - name: get user name
        run: |
<<<<<<< HEAD
          aws sts get-caller-identity;
	  ls;
          cd cnf; 
	  aws s3 aws cloudformation create-stack --stack-name s3-deploy --template-body file://cfn_deploy_s3.yaml;
          echo test, and deploy your project.
=======
              aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        continue-on-error: true


>>>>>>> 3aecbfacd2f08a827bf2a4389d0994d3ee5caa53
