name: s3 deploy
on:
  push:
    branches: 
      - main
    paths:
      - cfn/**
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: pull repo
        uses: actions/checkout@v3
 
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        continue-on-error: true

      - name: determine if s3 stack has been created 
        run: |
              aws cloudformation --region us-east-1 describe-stacks --stack-name deploy-s3
              if [[ "$?" == 0 ]]
              then
                 echo "BUCKET_CREATED=true" >> "$GITHUB_ENV"
              else
                 echo "BUCKET_CREATED=false" >> "$GITHUB_ENV"
              fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        continue-on-error: true


      - name: create s3
        if: env.BUCKET_CREATED == false
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: deploy-s3
          template: cfn/cfn_deploy_s3.yaml  
        continue-on-error: true

